version: "3.8"

services:

  frontend_app: 
    hostname: frontend_app
    container_name: frontend_app
    restart: always
    build: 
      context: frontend/
    image: frontend_app
    ports: 
      - "3000:80"
    depends_on:
      - backend_app
    networks:
      - three-tier-net 

  backend_app:
    hostname: backend_app
    container_name: backend_app
    restart: always
    build: 
      context: backend/
    image: backend_app
    ports: 
      - "3500:3500"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql123
      - MYSQL_DATABASE=school
    depends_on:
      - db
    networks:
      - three-tier-net

  db:
    hostname: mysql
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=school
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - three-tier-net
 
volumes:
  mysql-data:
    name: mysql-data

networks:
  three-tier-net:
    name: three-tier-net
    driver: bridge
